# 
#   Copyright (C) 2016-2018 Philipp Paulweber
#   All rights reserved.
# 
#   Developed by: Philipp Paulweber
#                 <https://github.com/ppaulweber/ci>
# 
#   This file is part of ci.
# 
#   ci is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# 
#   ci is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License
#   along with ci. If not, see <http://www.gnu.org/licenses/>.
# 

* ci

TBD

** Copyright and License

The copyright holder of 
=ci= is the Philipp Paulweber ([[https://github.com/ppaulweber][@ppaulweber]]) 
and the used license of 
=ci= is the [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3]].


*** Notice

#+begin_src

Copyright (C) 2016-2018 Philipp Paulweber
All rights reserved.

Developed by: Philipp Paulweber
              <https://github.com/ppaulweber/ci>

This file is part of ci.

ci is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ci is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with ci. If not, see <http://www.gnu.org/licenses/>.

#+end_src
